export interface SocketMessageHandler {
	handle: Function
}

export enum Command {
	NEW_PLAYER = "NEW_PLAYER",
	BET_PHASE_STARTS = "BET_PHASE_STARTS",
	INSURANCE_PHASE_STARTS = "INSURANCE_PHASE_STARTS",
	WAITING_PLAYER_ACTION = "WAITING_PLAYER_ACTION",
	LOGIN = "LOGIN",
	ROUND_COMPLETED = "ROUND_COMPLETED",
	PLAYER_LEFT = "PLAYER_LEFT",
	STATUS_UPDATE = "STATUS_UPDATE",
	OPEN_TABLE = "OPEN_TABLE",
	TIMED_OUT = "TIMED_OUT",
	INITIAL_DEAL_DONE = "INITIAL_DEAL_DONE"
}
