# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Full Casino build in roulette branch

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B clean package --file ${GITHUB_WORKSPACE}/codes/backend/casino/pom.xml
    - name: List target files
      run: | 
          cd codes/backend/casino/common
          tree target
          cd ..
          cd service
          tree target
          cd ..
          cd web
          pwd
          tree target
          cd ..
          cd blackjack
          tree target
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
     # uses: advanced-security/maven-dependency-submission-action@v1 --d ${GITHUB_WORKSPACE}/codes/backend/casino/
     
    #Currently the action is limited to single module Maven projects, with a future update that will add support for multi-module based projects.
    
  publish:
    runs-on: ubuntu-latest
    
    needs: build
    steps:
      - name: print current directory
        run: |
            tree
            ls -a
      - name: cache maven files
        uses: actions/cache@v3
        env:
            cache-name: cache-files
        with:
          name: artifact
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
