package com.casino.common.user;

public enum Title {
	NEW_PLAYER, BET_PHASE_STARTS, INSURANCE_PHASE_STARTS, SERVER_WAITS_PLAYER_ACTION, LOGIN, ROUND_COMPLETED, PLAYER_LEFT, STATUS_UPDATE, WATCHER_JOIN, TIMED_OUT
}
