package com.casino.common.user;

public enum Title {
	NEW_PLAYER, 
	BET_PHASE_STARTS, 
	INSURANCE_PHASE_STARTS, 
	INITIAL_DEAL_DONE, 
	WAITING_PLAYER_ACTION, 
	LOGIN, 
	ROUND_COMPLETED, 
	PLAYER_LEFT, 
	STATUS_UPDATE, 
	OPEN_TABLE, 
	TIMED_OUT, 
	SIT_OUT
}
